// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auction.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuction = `-- name: CreateAuction :one
INSERT INTO
    auctions (title, basePrice, highestBid, state, ownerId)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id
`

type CreateAuctionParams struct {
	Title      string        `json:"title"`
	Baseprice  int64         `json:"baseprice"`
	Highestbid int64         `json:"highestbid"`
	State      AuctionStatus `json:"state"`
	Ownerid    int64         `json:"ownerid"`
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.Title,
		arg.Baseprice,
		arg.Highestbid,
		arg.State,
		arg.Ownerid,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAuctionByID = `-- name: GetAuctionByID :one
SELECT
    id,
    title,
    ownerId,
    winnerId,
    basePrice,
    highestBid,
    state
FROM
    auctions
WHERE
    id = $1
`

func (q *Queries) GetAuctionByID(ctx context.Context, id int64) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionByID, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Ownerid,
		&i.Winnerid,
		&i.Baseprice,
		&i.Highestbid,
		&i.State,
	)
	return i, err
}

const placeBid = `-- name: PlaceBid :exec
INSERT INTO
    bids (auctionId, bidderId, amount)
VALUES
    ($1, $2, $3)
`

type PlaceBidParams struct {
	Auctionid int64 `json:"auctionid"`
	Bidderid  int64 `json:"bidderid"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) PlaceBid(ctx context.Context, arg PlaceBidParams) error {
	_, err := q.db.Exec(ctx, placeBid, arg.Auctionid, arg.Bidderid, arg.Amount)
	return err
}

const updateAuctionWinner = `-- name: UpdateAuctionWinner :exec
UPDATE auctions
SET
    winnerId = $1,
    highestBid = $2
WHERE
    id = $3
`

type UpdateAuctionWinnerParams struct {
	Winnerid   pgtype.Int8 `json:"winnerid"`
	Highestbid int64       `json:"highestbid"`
	ID         int64       `json:"id"`
}

func (q *Queries) UpdateAuctionWinner(ctx context.Context, arg UpdateAuctionWinnerParams) error {
	_, err := q.db.Exec(ctx, updateAuctionWinner, arg.Winnerid, arg.Highestbid, arg.ID)
	return err
}
