// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuctionStatus string

const (
	AuctionStatusOngoing AuctionStatus = "ongoing"
	AuctionStatusEnded   AuctionStatus = "ended"
)

func (e *AuctionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuctionStatus(s)
	case string:
		*e = AuctionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuctionStatus: %T", src)
	}
	return nil
}

type NullAuctionStatus struct {
	AuctionStatus AuctionStatus `json:"auction_status"`
	Valid         bool          `json:"valid"` // Valid is true if AuctionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuctionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuctionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuctionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuctionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuctionStatus), nil
}

type Auction struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Ownerid     int64              `json:"ownerid"`
	Winnerid    pgtype.Int8        `json:"winnerid"`
	Baseprice   int64              `json:"baseprice"`
	Highestbid  int64              `json:"highestbid"`
	State       AuctionStatus      `json:"state"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
}

type Bid struct {
	ID        int64 `json:"id"`
	Auctionid int64 `json:"auctionid"`
	Bidderid  int64 `json:"bidderid"`
	Amount    int64 `json:"amount"`
}

type User struct {
	ID int64 `json:"id"`
}
