// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateAuction(ctx context.Context, arg CreateAuctionParams) (int64, error)
	EndAuction(ctx context.Context, id int64) error
	GetAuctionByID(ctx context.Context, id int64) (Auction, error)
	GetCompletedAuctions(ctx context.Context) ([]Auction, error)
	GetOngoingAuctions(ctx context.Context) ([]int64, error)
	PlaceBid(ctx context.Context, arg PlaceBidParams) error
	UpdateAuctionWinner(ctx context.Context, arg UpdateAuctionWinnerParams) error
}

var _ Querier = (*Queries)(nil)
